name: C++ CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Compile tests
      run: g++ -std=c++17 tests/tests.cpp T_ConsoleLab/Reverse_polish_notation.cpp T_ConsoleLab/Polish_notation.cpp T_ConsoleLab/utils.cpp -o test

    - name: Run tests
      run: ./test
